name: "Release"

on:
    push:
        tags:
            - "v*"

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    CARGO_TERM_COLOR: always

jobs:
    fmt-check:
        name: Format Check
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - uses: actions/checkout@v4
            - uses: moonrepo/setup-rust@v1
              with:
                  channel: nightly
                  components: rustfmt
                  cache-base: "^master$"
            - run: cargo fmt --check

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: moonrepo/setup-rust@v1
              with:
                  channel: stable
                  components: clippy
                  cache-base: "^master$"
            - run: cargo clippy -- -D warnings

    build-cross-platform:
        name: Build ${{ matrix.build.NAME }}
        needs: lint
        runs-on: ${{ matrix.build.OS }}
        strategy:
            fail-fast: false
            matrix:
                build:
                    - {
                          NAME: linux-x64,
                          OS: ubuntu-latest,
                          TOOLCHAIN: stable,
                          TARGET: x86_64-unknown-linux-gnu,
                      }
                    - {
                          NAME: linux-arm64,
                          OS: ubuntu-latest,
                          TOOLCHAIN: stable,
                          TARGET: aarch64-unknown-linux-gnu,
                      }
                    - {
                          NAME: windows-x64,
                          OS: windows-latest,
                          TOOLCHAIN: stable,
                          TARGET: x86_64-pc-windows-msvc,
                      }
                    - {
                          NAME: windows-arm64,
                          OS: windows-latest,
                          TOOLCHAIN: stable,
                          TARGET: aarch64-pc-windows-msvc,
                      }
                    - {
                          NAME: darwin-x64,
                          OS: macos-14,
                          TOOLCHAIN: stable,
                          TARGET: x86_64-apple-darwin,
                      }
                    - {
                          NAME: darwin-arm64,
                          OS: macos-14,
                          TOOLCHAIN: stable,
                          TARGET: aarch64-apple-darwin,
                      }
        steps:
            - uses: actions/checkout@v4

            - uses: moonrepo/setup-rust@v1
              with:
                  channel: ${{ matrix.build.TOOLCHAIN }}
                  cache-base: "^master$"
                  targets: ${{ matrix.build.TARGET }}

            - name: Setup ARM64 cross-compilation
              if: matrix.build.TARGET == 'aarch64-unknown-linux-gnu'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y gcc-aarch64-linux-gnu

            - name: Build binary
              run: cargo build --release --locked --target ${{ matrix.build.TARGET }}
              env:
                  PKG_CONFIG_ALLOW_CROSS: ${{ matrix.build.TARGET == 'aarch64-unknown-linux-gnu' && '1' || '' }}
                  PKG_CONFIG_PATH: ${{ matrix.build.TARGET == 'aarch64-unknown-linux-gnu' && '/usr/lib/aarch64-linux-gnu/pkgconfig' || '' }}
                  CC_aarch64_unknown_linux_gnu: ${{ matrix.build.TARGET == 'aarch64-unknown-linux-gnu' && 'aarch64-linux-gnu-gcc' || '' }}
                  AR_aarch64_unknown_linux_gnu: ${{ matrix.build.TARGET == 'aarch64-unknown-linux-gnu' && 'aarch64-linux-gnu-ar' || '' }}
                  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: ${{ matrix.build.TARGET == 'aarch64-unknown-linux-gnu' && 'aarch64-linux-gnu-gcc' || '' }}

            - name: Prepare binary (Unix)
              if: matrix.build.OS != 'windows-latest'
              run: |
                  mkdir -p dist
                  cp target/${{ matrix.build.TARGET }}/release/sunny dist/
                  chmod +x dist/sunny

            - name: Prepare binary (Windows)
              if: matrix.build.OS == 'windows-latest'
              run: |
                  mkdir dist
                  cp target/${{ matrix.build.TARGET }}/release/sunny.exe dist/

            - name: Upload binary artifact
              uses: actions/upload-artifact@v4
              with:
                  name: sunny-cli-${{ matrix.build.NAME }}
                  path: dist/
                  retention-days: 1

    publish-cargo:
        name: Publish to Cargo
        needs: [build-cross-platform, lint]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: moonrepo/setup-rust@v1
              with:
                  channel: stable
                  cache-base: "^master$"
            - name: Publish to crates.io
              run: cargo publish --token ${{ env.CARGO_TOKEN }}

    publish-npm:
        name: Publish NPM packages
        needs: [build-cross-platform, lint]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  registry-url: "https://registry.npmjs.org"
                  scope: "@jamesukiyo"

            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts

            - name: Setup npm packages
              run: |
                  # copy binaries to their respective package directories
                  for platform in linux-x64 linux-arm64 windows-x64 windows-arm64 darwin-x64 darwin-arm64; do
                    if [ -d "artifacts/sunny-cli-$platform" ]; then
                      echo "Copying binaries for $platform"
                      cp -v artifacts/sunny-cli-$platform/* packages/sunny-cli-$platform/
                      ls -la packages/sunny-cli-$platform/
                    else
                      echo "Error: No artifact found for $platform"
                      exit 1
                    fi
                  done

            - name: Publish platform packages
              run: |
                  publish_with_retry() {
                    local package_dir=$1
                    local max_attempts=5
                    local attempt=1
                    local base_delay=10

                    while [ $attempt -le $max_attempts ]; do
                      echo "Attempt $attempt/$max_attempts: Publishing $(basename $package_dir)"
                      cd "$package_dir"

                      if npm publish --access public; then
                        echo "Successfully published $(basename $package_dir)"
                        cd ../..
                        return 0
                      else
                        echo "Failed to publish $(basename $package_dir) (attempt $attempt)"
                        cd ../..

                        if [ $attempt -lt $max_attempts ]; then
                          local delay=$((base_delay * attempt))
                          echo "Waiting ${delay}s before retry..."
                          sleep $delay
                        fi
                      fi

                      attempt=$((attempt + 1))
                    done

                    echo "Failed to publish $(basename $package_dir) after $max_attempts attempts"
                    return 1
                  }

                  for platform in linux-x64 linux-arm64 windows-x64 windows-arm64 darwin-x64 darwin-arm64; do
                    if publish_with_retry "packages/sunny-cli-$platform"; then
                      echo "Waiting 30s before next package to avoid rate limits..."
                      sleep 30
                    else
                      echo "Failed to publish sunny-cli-$platform"
                      exit 1
                    fi
                  done
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish main package
              run: |
                  publish_with_retry() {
                    local package_dir=$1
                    local max_attempts=5
                    local attempt=1
                    local base_delay=10

                    while [ $attempt -le $max_attempts ]; do
                      echo "Attempt $attempt/$max_attempts: Publishing main package"
                      cd "$package_dir"

                      if npm publish --access public; then
                        echo "Successfully published main package"
                        cd ../..
                        return 0
                      else
                        echo "Failed to publish main package (attempt $attempt)"
                        cd ../..

                        if [ $attempt -lt $max_attempts ]; then
                          local delay=$((base_delay * attempt))
                          echo "Waiting ${delay}s before retry..."
                          sleep $delay
                        fi
                      fi

                      attempt=$((attempt + 1))
                    done

                    echo "Failed to publish main package after $max_attempts attempts"
                    return 1
                  }

                  echo "Waiting 60s before publishing main package..."
                  sleep 60
                  publish_with_retry "packages/base"

    github-release:
        name: Create GitHub Release
        needs: [build-cross-platform, publish-cargo, publish-npm, lint]
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts

            - name: Create release archives
              run: |
                  mkdir -p release-assets

                  for platform in linux-x64 linux-arm64 darwin-x64 darwin-arm64; do
                    if [ -d "artifacts/sunny-cli-$platform" ]; then
                      cd artifacts/sunny-cli-$platform
                      tar -czf ../../release-assets/sunny-cli-$platform.tar.gz *
                      cd ../..
                    fi
                  done

                  for platform in windows-x64 windows-arm64; do
                    if [ -d "artifacts/sunny-cli-$platform" ]; then
                      cd artifacts/sunny-cli-$platform
                      zip -r ../../release-assets/sunny-cli-$platform.zip *
                      cd ../..
                    fi
                  done

            - uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
                  files: release-assets/*
